import 'package:flutter/material.dart';

class AppStrings {
  AppStrings._();

  static final Map<String, Map<String, String>> _localized = {
    'ar': {
      'app_name': 'تطبيق كفيل لرعاية وكفالة الأيتام',
      'app_tagline': 'منصة رقمية متخصصة في رعاية وكفالة الأيتام وتسهيل إدارة الكفالات والتواصل بين الكفلاء والمؤسسة.',
      'nav_home': 'الرئيسية',
      'nav_orphans': 'الأيتام',
      'nav_sponsorships': 'كفالاتي',
      'nav_profile': 'حسابي',
      'loading': 'جاري التحميل...',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'full_name': 'الاسم الكامل',
      'forgot_password': 'نسيت كلمة المرور؟',
      'remember_me': 'تذكرني',
      'no_account': 'ليس لديك حساب؟',
      'have_account': 'لديك حساب بالفعل؟',
      'sign_up': 'سجل الآن',
      'sign_in': 'تسجيل الدخول',
      'welcome_back': 'سجل دخولك للمتابعة',
      'join_us': 'انضم إلينا وابدأ رحلة العطاء',
      'welcome': 'مرحباً',
      'good_morning': 'صباح الخير',
      'good_evening': 'مساء الخير',
      'overview': 'نظرة عامة',
      'total_orphans': 'إجمالي الأيتام',
      'available_orphans': 'المحتاجون للكفالة',
      'sponsored_orphans': 'الأيتام المكفولين',
      'active_sponsorships': 'الكفالات النشطة',
      'completed_sponsorships': 'الكفالات المنتهية',
      'coverage_rate': 'نسبة التغطية',
      'out_of': 'من',
      'orphans_sponsored': 'أيتام مكفولون',
      'quick_actions': 'إجراءات سريعة',
      'favorites': 'المفضلة',
      'notifications': 'الإشعارات',
      'reports': 'التقارير',
      'profile': 'الملف الشخصي',
      'recent_activity': 'أحدث النشاطات',
      'recent_orphans': 'أحدث الأيتام',
      'recent_notifications': 'أحدث الإشعارات',
      'view_all': 'عرض الكل',
      'added_recently': 'تمت الإضافة حديثاً',
      'orphans_title': 'الأيتام',
      'search_orphans': 'بحث عن يتيم...',
      'all': 'الجميع',
      'needs_sponsorship': 'يحتاج كفالة',
      'sponsored': 'مكفول',
      'age': 'العمر',
      'gender': 'الجنس',
      'location': 'الموقع',
      'health_status': 'الحالة الصحية',
      'education_level': 'المستوى التعليمي',
      'story': 'القصة',
      'date_added': 'تاريخ الإضافة',
      'request_sponsorship': 'طلب كفالة',
      'no_orphans': 'لا يوجد أيتام',
      'sort_by': 'ترتيب حسب',
      'sort_name': 'الاسم',
      'sort_age': 'العمر',
      'sort_newest': 'الأحدث',
      'years_old': 'سنة',
      'male': 'ذكر',
      'female': 'أنثى',
      'favorites_title': 'المفضلة',
      'no_favorites': 'لا توجد مفضلة',
      'no_favorites_desc': 'قم بإضافة الأيتام إلى المفضلة لمتابعتهم',
      'my_sponsorships': 'كفالاتي',
      'new_sponsorship': 'طلب كفالة جديد',
      'active': 'النشطة',
      'pending': 'قيد الانتظار',
      'history': 'السجل',
      'sponsorship_type': 'نوع الكفالة',
      'monthly': 'شهري',
      'quarterly': 'ربع سنوي',
      'yearly': 'سنوي',
      'one_time': 'مرة واحدة',
      'amount': 'المبلغ',
      'notes': 'ملاحظات',
      'submit': 'تقديم طلب الكفالة',
      'submitting': 'جاري التقديم...',
      'submitted_success': 'تم تقديم طلب الكفالة بنجاح',
      'no_active': 'لا توجد كفالات نشطة',
      'no_pending': 'لا توجد كفالات قيد الانتظار',
      'no_history': 'لا توجد كفالات في السجل',
      'riyal': 'ريال',
      'sponsorship_path': 'مسار الكفالة',
      'request_sent': 'تم إرسال الطلب',
      'request_approved': 'تمت الموافقة',
      'sponsorship_started': 'بدأت الكفالة',
      'sponsorship_active': 'الكفالة نشطة',
      'ending_soon': 'تنتهي قريبًا',
      'sponsorship_ended': 'انتهت الكفالة',
      'request_rejected': 'تم الرفض',
      'sponsorship_cancelled': 'تم الإلغاء',
      'reports_title': 'التقارير والإحصائيات',
      'total_sponsorships': 'إجمالي الكفالات',
      'total_donated': 'إجمالي المبلغ المتبرع به',
      'last_activity': 'آخر نشاط',
      'average_duration': 'متوسط المدة',
      'edit_profile': 'تعديل الملف الشخصي',
      'change_password': 'تغيير كلمة المرور',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'account_status': 'حالة الحساب',
      'registration_date': 'تاريخ التسجيل',
      'account_active': 'نشط',
      'language': 'اللغة',
      'appearance': 'المظهر',
      'light_mode': 'الوضع الفاتح',
      'dark_mode': 'الوضع الداكن',
      'system_mode': 'وضع النظام',
      'enable_notifications': 'تفعيل الإشعارات',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_of_use': 'شروط الاستخدام',
      'about_app': 'حول التطبيق',
      'contact_support': 'تواصل مع الدعم',
      'version': 'الإصدار',
      'contact_us': 'اتصل بنا',
      'email_address': 'support@orphans.org',
      'phone_number': '+966 55 000 0000',
      'whatsapp': '+966 55 000 0000',
      'address': 'المملكة العربية السعودية',
      'working_hours': 'ساعات العمل',
      'working_hours_detail': 'الأحد - الخميس: 9 صباحاً - 5 مساءً',
      'about_title': 'حول التطبيق',
      'app_description': 'تطبيق متكامل لإدارة كفالة الأيتام وتمكين المحسنين من التواصل مع الأيتام المحتاجين للرعاية.',
      'university': 'الجامعة',
      'department': 'القسم',
      'supervisor': 'المشرف',
      'team': 'الفريق',
      'year': 'السنة',
      'error_title': 'حدث خطأ',
      'retry': 'إعادة المحاولة',
      'no_internet': 'لا يوجد اتصال بالإنترنت',
      'unknown_error': 'حدث خطأ غير متوقع',
      'no_data': 'لا توجد بيانات',
      'save': 'حفظ',
      'now': 'الآن',
      'minutes_ago': 'منذ %d دقيقة',
      'hours_ago': 'منذ %d ساعة',
      'days_ago': 'منذ %d يوم',
      'weeks_ago': 'منذ %d أسبوع',
      'sponsorship_info': 'معلومات أساسية',
      'available': 'يحتاج كفالة',
      'sponsored_status': 'مكفول',
      'no_results': 'لا توجد نتائج مطابقة للفلتر المحدد',
      'advanced_filters': 'فلترة متقدمة',
      'less_than_5': 'أقل من 5',
      'range_5_10': '5-10',
      'range_10_15': '10-15',
      'greater_than_15': 'أكبر من 15',
      'healthy': 'سليم',
      'needs_care': 'يحتاج رعاية',
      'select_orphan': 'اختر يتيماً',
      'choose_orphan_prompt': 'يرجى اختيار يتيم',
      'required_field': 'هذا الحقل مطلوب',
      'invalid_email': 'البريد الإلكتروني غير صحيح',
      'password_too_short': 'كلمة المرور قصيرة جداً (6 أحرف على الأقل)',
      'passwords_mismatch': 'كلمة المرور غير متطابقة',
      'name_too_short': 'الاسم قصير جداً (3 أحرف على الأقل)',
      'phone': 'رقم الهاتف',
      'address_label': 'العنوان',
      'invalid_amount': 'المبلغ غير صحيح',
      'amount_too_high': 'المبلغ كبير جداً',
      'amount_hint': '200',
      'notes_hint': 'أي ملاحظات إضافية...',
      'error_occurred': 'حدث خطأ غير متوقع. حاول مرة أخرى.',
      'sponsorship_created': 'تم تقديم طلب الكفالة بنجاح',
      'no_sponsorships_active': 'لم تقم بكفالة أي يتيم بعد',
      'sponsorships_pending_review': 'سيتم مراجعة طلباتك قريباً',
      'sponsorships_history_empty': 'سيظهر هنا تاريخ كفالاتك',
      'browse_orphans': 'تصفح الأيتام',
      'new_sponsorship_btn': 'كفالة جديدة',
      'orphan_details': 'تفاصيل اليتيم',
      'status_summary': 'ملخص الحالة',
      'recent_sponsorships': 'الكفالات الأخيرة',
      'no_reports': 'لا توجد تقارير',
      'no_reports_desc': 'لم تقم بأي كفالة بعد',
      'no_favorites_desc_alt': 'يمكنك إضافة أيتام إلى المفضلة من صفحة التفاصيل',
      'sponsorship_not_found': 'لم يتم العثور على الكفالة',
      'sponsorship_not_found_desc': 'قد تكون هذه الكفالة غير متاحة أو تم حذفها',
      'page_not_found': 'الصفحة غير موجودة',
      'remaining': 'متبقي',
      'unsponsored_orphans': 'غير مكفولين',
      'total_sponsors': 'إجمالي الكفلاء',
      'sort_by_name': 'الاسم',
      'sort_by_age': 'العمر',
      'newest_first': 'الأحدث أولاً',
      'no_orphans_found': 'لم يتم العثور على أيتام',
      'no_orphans_found_desc': 'حاول تغيير معايير البحث',
      'file_number': 'رقم الملف',
      'birth_date': 'تاريخ الميلاد',
      'religion': 'الديانة',
      'nationality': 'الجنسية',
      'branch': 'الفرع',
      'personal_info': 'معلومات شخصية',
      'education_health': 'التعليم والصحة',
      'education_status': 'الحالة التعليمية',
      'school': 'المدرسة',
      'academic_level': 'المستوى الدراسي',
      'talents': 'المواهب',
      'quran_memorization': 'حفظ القرآن',
      'family_info': 'معلومات الأسرة',
      'father_death_cause': 'سبب وفاة الأب',
      'mother_name': 'اسم الأم',
      'mother_status': 'حالة الأم',
      'guardian_name': 'اسم المعيل',
      'guardian_relation': 'صلة القرابة',
      'guardian_phone': 'هاتف المعيل',
      'sponsorship_details': 'تفاصيل الكفالة',
      'sponsor_name': 'اسم الكفيل',
      'monthly_amount': 'المبلغ الشهري',
      'status': 'الحالة',
      'start_date': 'تاريخ البداية',
      'end_date': 'تاريخ النهاية',
      'sponsor_now': 'كفالة هذا اليتيم الآن',
      'sponsored_currently': 'مكفول حالياً',
      'sponsorship_stopped': 'كفالة هذا اليتيم متوقفة ويحتاج إلى كفيل جديد',
      'sar': 'ر.س',
      'no_sponsorships': 'لا توجد كفالات',
      'no_sponsorships_desc': 'لم تقم بكفالة أي يتيم بعد. ابدأ الآن!',
      'no_items': 'لا توجد عناصر',
      'remaining_days': 'الأيام المتبقية',
      'days': 'يوم',
      'no_notifications': 'لا توجد إشعارات',
      'no_notifications_desc': 'سوف تظهر الإشعارات هنا عند توفرها',
      'mark_all_read': 'تحديد الكل كمقروء',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'older': 'أقدم',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'theme': 'المظهر',
      'light': 'فاتح',
      'dark': 'داكن',
      'system': 'النظام',
      'push_notifications': 'إشعارات التطبيق',
      'push_notifications_desc': 'استلام إشعارات عن الكفالات والتحديثات',
      'app_version': 'إصدار التطبيق',
      'about': 'حول',
      'contact': 'اتصل بنا',
      'logout_confirmation': 'هل أنت متأكد من تسجيل الخروج؟',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'password_changed': 'تم تغيير كلمة المرور بنجاح',
      'member_since': 'عضو منذ',
      'total': 'المجموع',
      'orphans': 'الأيتام',
      'user': 'المستخدم',
      'name': 'الاسم',
      'financial': 'مالي',
      'educational': 'تعليمي',
      'medical': 'طبي',
      'completed': 'مكتمل',
      'inactive': 'غير نشط',
      'ended': 'منتهي',
      'help_center': 'مركز المساعدة',
      'help_intro_title': 'مرحباً بك في تطبيق كفيل',
      'help_intro_desc': 'تطبيق كفيل هو منصة رقمية متخصصة في إدارة كفالة الأيتام، تتيح للمحسنين تصفح الأيتام المحتاجين للكفالة، وتقديم طلبات الكفالة، ومتابعة الكفالات الحالية، والتواصل مع المؤسسة المعنية. يهدف التطبيق إلى تسهيل عملية الكفالة وجعلها أكثر شفافية وسهولة.',
      'help_getting_started': 'بدء الاستخدام',
      'help_getting_started_desc': 'لبدء استخدام التطبيق، يجب عليك إنشاء حساب جديد عبر شاشة التسجيل. أدخل اسمك الكامل، بريدك الإلكتروني، كلمة المرور، ورقم هاتفك. بعد التسجيل، يمكنك تسجيل الدخول باستخدام بريدك الإلكتروني وكلمة المرور. إذا كان لديك حساب بالفعل، يمكنك تسجيل الدخول مباشرة.',
      'help_dashboard': 'الشاشة الرئيسية',
      'help_dashboard_desc': 'تعرض الشاشة الرئيسية نظرة عامة على إحصائياتك: إجمالي الأيتام (المكفولون من قبلك + المتاحون للكفالة)، الأيتام المكفولين، الكفالات النشطة، والكفالات المنتهية. كما تظهر بطاقة الأيتام غير المكفولين الذين يحتاجون إلى كفالة. يمكنك استخدام الأزرار السريعة للانتقال إلى الأيتام، الكفالات، التقارير، والملف الشخصي. ملاحظة: خيار الإشعارات متاح فقط لحسابات المشرفين.',
      'help_orphans': 'قسم الأيتام',
      'help_orphans_desc': 'يمكنك تصفح قائمة الأيتام مع ثلاثة خيارات تصفية: "الجميع" ويعرض الأيتام المكفولين من قبلك مع الأيتام المتاحين للكفالة، "مكفول" ويعرض الأيتام الذين تكفلهم فقط، "يحتاج كفالة" ويعرض الأيتام المتاحين للكفالة فقط. استخدم شريط البحث للعثور على يتيم بالاسم، ورتب الأيتام حسب الأحدث أو الاسم أو العمر. اضغط على بطاقة اليتيم لعرض التفاصيل الكاملة. تظهر حالة اليتيم كـ "مكفول حالياً" للكفالات النشطة، أو "كفالة هذا اليتيم متوقفة ويحتاج إلى كفيل جديد" للكفالات المنتهية، أو "يحتاج كفالة" لليتيم غير المكفول.',
      'help_sponsorships': 'قسم الكفالات',
      'help_sponsorships_desc': 'يعرض هذا القسم جميع كفالاتك مقسمة إلى ثلاث تبويبات: "الكفالات النشطة" وتظهر الكفالات الجاري سريانها، "الكفالات المنتهية" وتظهر الكفالات التي انتهت أو توقفت، و"السجل" ويعرض جميع الكفالات. يمكنك تقديم طلب كفالة جديد بالضغط على زر الكفالة الجديدة. اختر اليتيم، حدد نوع الكفالة (مالية، تعليمية، طبية)، وأدخل المبلغ الشهري. يمكنك متابعة مسار الكفالة عبر شاشة المتابعة.',
      'help_reports': 'التقارير والإحصائيات',
      'help_reports_desc': 'يوفر قسم التقارير إحصائيات مفصلة عن كفالاتك: إجمالي عدد الكفالات، الكفالات النشطة، الكفالات المنتهية، إجمالي المبلغ المتبرع به، ومتوسط مدة الكفالة. يمكنك تحديث البيانات بسحب الشاشة للأسفل.',
      'help_notifications': 'الإشعارات',
      'help_notifications_desc': 'تتوفر الإشعارات لحسابات المشرفين فقط. تصلك إشعارات عند تقديم طلب كفالة جديد أو تحديث حالة الكفالة. يمكنك تحديد الإشعارات كمقروءة بالضغط عليها، أو تحديد الكل كمقروء من زر القائمة. يظهر عدد الإشعارات غير المقروءة على أيقونة الجرس في الشاشة الرئيسية.',
      'help_profile': 'الملف الشخصي',
      'help_profile_desc': 'من شاشة الملف الشخصي يمكنك عرض معلومات حسابك وتعديلها (الاسم، البريد الإلكتروني، الهاتف، العنوان). كما يمكنك تغيير كلمة المرور، وعرض إحصائياتك الشخصية: الكفالات النشطة، إجمالي التبرعات، وعدد الأيتام المكفولين. يمكنك أيضاً الانتقال إلى صفحة "حول التطبيق" و"اتصل بنا". ملاحظة: خيار الإشعارات في الملف الشخصي متاح فقط لحسابات المشرفين.',
      'help_settings': 'الإعدادات',
      'help_settings_desc': 'من خلال شاشة الإعدادات يمكنك تغيير لغة التطبيق بين العربية والإنجليزية، تبديل المظهر بين الفاتح والداكن والنظام، وتفعيل أو إلغاء إشعارات التطبيق.',
      'help_faq': 'الأسئلة الشائعة',
      'help_faq_q1': 'كيف يمكنني كفالة يتيم؟',
      'help_faq_a1': 'يمكنك كفالة يتيم بالانتقال إلى قائمة الأيتام، اختيار يتيم غير مكفول، الضغط على زر "كفالة هذا اليتيم الآن"، ثم تعبئة نموذج طلب الكفالة وتقديمه.',
      'help_faq_q2': 'كم تكلفة كفالة يتيم؟',
      'help_faq_a2': 'يمكنك تحديد المبلغ الشهري الذي ترغب في التبرع به عند تقديم طلب الكفالة. لا يوجد حد أدنى إلزامي، ويمكنك اختيار المبلغ المناسب لك.',
      'help_faq_q3': 'كيف يمكنني متابعة كفالاتي؟',
      'help_faq_a3': 'يمكنك متابعة جميع كفالاتك من خلال قسم "كفالاتي" في الشريط السفلي. هناك يمكنك الاطلاع على حالة كل كفالة وتفاصيلها.',
      'help_faq_q4': 'كيف يمكنني التواصل مع الدعم؟',
      'help_faq_a4': 'يمكنك التواصل مع فريق الدعم من خلال قسم "اتصل بنا" المتاح في قائمة الملف الشخصي، حيث ستجد البريد الإلكتروني وأرقام الهواتف.',
      'help_contact': 'الدعم الفني',
      'help_contact_desc': 'إذا واجهت أي مشكلة أو كان لديك استفسار، لا تتردد في التواصل مع فريق الدعم الفني عبر البريد الإلكتروني أو الهاتف أو واتساب المتاحة في قسم "اتصل بنا".',
    },
    'en': {
      'app_name': 'تطبيق كفيل لرعاية وكفالة الأيتام',
      'app_tagline': 'منصة رقمية متخصصة في رعاية وكفالة الأيتام وتسهيل إدارة الكفالات والتواصل بين الكفلاء والمؤسسة.',
      'nav_home': 'Home',
      'nav_orphans': 'Orphans',
      'nav_sponsorships': 'Sponsorships',
      'nav_profile': 'Profile',
      'loading': 'Loading...',
      'login': 'Login',
      'register': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',
      'forgot_password': 'Forgot Password?',
      'remember_me': 'Remember Me',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'sign_up': 'Sign Up',
      'sign_in': 'Sign In',
      'welcome_back': 'Welcome back',
      'join_us': 'Join us and start your journey',
      'welcome': 'Welcome',
      'good_morning': 'Good Morning',
      'good_evening': 'Good Evening',
      'overview': 'Overview',
      'total_orphans': 'Total Orphans',
      'available_orphans': 'Needs Sponsorship',
      'sponsored_orphans': 'Sponsored Orphans',
      'active_sponsorships': 'Active Sponsorships',
      'completed_sponsorships': 'Completed Sponsorships',
      'coverage_rate': 'Coverage Rate',
      'out_of': 'out of',
      'orphans_sponsored': 'orphans sponsored',
      'quick_actions': 'Quick Actions',
      'favorites': 'Favorites',
      'notifications': 'Notifications',
      'reports': 'Reports',
      'profile': 'Profile',
      'recent_activity': 'Recent Activity',
      'recent_orphans': 'Recent Orphans',
      'recent_notifications': 'Recent Notifications',
      'view_all': 'View All',
      'added_recently': 'Added recently',
      'orphans_title': 'Orphans',
      'search_orphans': 'Search orphans...',
      'all': 'All',
      'needs_sponsorship': 'Needs Sponsorship',
      'sponsored': 'Sponsored',
      'age': 'Age',
      'gender': 'Gender',
      'location': 'Location',
      'health_status': 'Health Status',
      'education_level': 'Education Level',
      'story': 'Story',
      'date_added': 'Date Added',
      'request_sponsorship': 'Request Sponsorship',
      'no_orphans': 'No orphans found',
      'sort_by': 'Sort by',
      'sort_name': 'Name',
      'sort_age': 'Age',
      'sort_newest': 'Newest',
      'years_old': 'years old',
      'male': 'Male',
      'female': 'Female',
      'favorites_title': 'Favorites',
      'no_favorites': 'No favorites',
      'no_favorites_desc': 'Add orphans to favorites to follow them',
      'my_sponsorships': 'My Sponsorships',
      'new_sponsorship': 'New Sponsorship',
      'active': 'Active',
      'pending': 'Pending',
      'history': 'History',
      'sponsorship_type': 'Sponsorship Type',
      'monthly': 'Monthly',
      'quarterly': 'Quarterly',
      'yearly': 'Yearly',
      'one_time': 'One Time',
      'amount': 'Amount',
      'notes': 'Notes',
      'submit': 'Submit Request',
      'submitting': 'Submitting...',
      'submitted_success': 'Sponsorship request submitted successfully',
      'no_active': 'No active sponsorships',
      'no_pending': 'No pending sponsorships',
      'no_history': 'No sponsorship history',
      'riyal': 'SAR',
      'sponsorship_path': 'Sponsorship Path',
      'request_sent': 'Request Sent',
      'request_approved': 'Approved',
      'sponsorship_started': 'Sponsorship Started',
      'sponsorship_active': 'Active',
      'ending_soon': 'Ending Soon',
      'sponsorship_ended': 'Completed',
      'request_rejected': 'Rejected',
      'sponsorship_cancelled': 'Cancelled',
      'reports_title': 'Reports & Statistics',
      'total_sponsorships': 'Total Sponsorships',
      'total_donated': 'Total Amount Donated',
      'last_activity': 'Last Activity',
      'average_duration': 'Average Duration',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'settings': 'Settings',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'account_status': 'Account Status',
      'registration_date': 'Registration Date',
      'account_active': 'Active',
      'language': 'Language',
      'appearance': 'Appearance',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'system_mode': 'System Mode',
      'enable_notifications': 'Enable Notifications',
      'privacy_policy': 'Privacy Policy',
      'terms_of_use': 'Terms of Use',
      'about_app': 'About',
      'contact_support': 'Contact Support',
      'version': 'Version',
      'contact_us': 'Contact Us',
      'email_address': 'support@orphans.org',
      'phone_number': '+966 55 000 0000',
      'whatsapp': '+966 55 000 0000',
      'address': 'Saudi Arabia',
      'working_hours': 'Working Hours',
      'working_hours_detail': 'Sun - Thu: 9:00 AM - 5:00 PM',
      'about_title': 'About',
      'app_description': 'A comprehensive platform for orphan sponsorship management, enabling benefactors to connect with orphans in need of care.',
      'university': 'University',
      'department': 'Department',
      'supervisor': 'Supervisor',
      'team': 'Team',
      'year': 'Year',
      'error_title': 'Error',
      'retry': 'Retry',
      'no_internet': 'No internet connection',
      'unknown_error': 'An unexpected error occurred',
      'no_data': 'No data available',
      'save': 'Save',
      'now': 'now',
      'minutes_ago': '%d minutes ago',
      'hours_ago': '%d hours ago',
      'days_ago': '%d days ago',
      'weeks_ago': '%d weeks ago',
      'sponsorship_info': 'Basic Information',
      'available': 'Needs Sponsorship',
      'sponsored_status': 'Sponsored',
      'no_results': 'No matching results for the selected filter',
      'advanced_filters': 'Advanced Filters',
      'less_than_5': 'Less than 5',
      'range_5_10': '5-10',
      'range_10_15': '10-15',
      'greater_than_15': 'Greater than 15',
      'healthy': 'Healthy',
      'needs_care': 'Needs Care',
      'select_orphan': 'Select orphan',
      'choose_orphan_prompt': 'Please select an orphan',
      'required_field': 'This field is required',
      'invalid_email': 'Invalid email address',
      'password_too_short': 'Password too short (min 6 characters)',
      'passwords_mismatch': 'Passwords do not match',
      'name_too_short': 'Name too short (min 3 characters)',
      'phone': 'Phone',
      'address_label': 'Address',
      'invalid_amount': 'Invalid amount',
      'amount_too_high': 'Amount too high',
      'amount_hint': '200',
      'notes_hint': 'Any additional notes...',
      'error_occurred': 'An unexpected error occurred. Please try again.',
      'sponsorship_created': 'Sponsorship request submitted successfully',
      'no_sponsorships_active': 'You haven\'t sponsored any orphan yet',
      'sponsorships_pending_review': 'Your requests will be reviewed soon',
      'sponsorships_history_empty': 'Your sponsorship history will appear here',
      'browse_orphans': 'Browse Orphans',
      'new_sponsorship_btn': 'New Sponsorship',
      'orphan_details': 'Orphan Details',
      'status_summary': 'Status Summary',
      'recent_sponsorships': 'Recent Sponsorships',
      'no_reports': 'No Reports',
      'no_reports_desc': 'You haven\'t made any sponsorships yet',
      'no_favorites_desc_alt': 'You can add orphans to favorites from the details page',
      'sponsorship_not_found': 'Sponsorship not found',
      'sponsorship_not_found_desc': 'This sponsorship may not be available or has been deleted',
      'page_not_found': 'Page not found',
      'remaining': 'Remaining',
      'unsponsored_orphans': 'Unsponsored',
      'total_sponsors': 'Total Sponsors',
      'sort_by_name': 'Name',
      'sort_by_age': 'Age',
      'newest_first': 'Newest First',
      'no_orphans_found': 'No orphans found',
      'no_orphans_found_desc': 'Try changing your search criteria',
      'file_number': 'File Number',
      'birth_date': 'Birth Date',
      'religion': 'Religion',
      'nationality': 'Nationality',
      'branch': 'Branch',
      'personal_info': 'Personal Info',
      'education_health': 'Education & Health',
      'education_status': 'Education Status',
      'school': 'School',
      'academic_level': 'Academic Level',
      'talents': 'Talents',
      'quran_memorization': 'Quran Memorization',
      'family_info': 'Family Info',
      'father_death_cause': 'Father\'s Death Cause',
      'mother_name': 'Mother\'s Name',
      'mother_status': 'Mother\'s Status',
      'guardian_name': 'Guardian Name',
      'guardian_relation': 'Guardian Relation',
      'guardian_phone': 'Guardian Phone',
      'sponsorship_details': 'Sponsorship Details',
      'sponsor_name': 'Sponsor Name',
      'monthly_amount': 'Monthly Amount',
      'status': 'Status',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'sponsor_now': 'Sponsor This Orphan Now',
      'sponsored_currently': 'Currently Sponsored',
      'sponsorship_stopped': 'Sponsorship for this orphan has stopped and needs a new sponsor',
      'sar': 'SAR',
      'no_sponsorships': 'No Sponsorships',
      'no_sponsorships_desc': 'You haven\'t sponsored any orphan yet. Start now!',
      'no_items': 'No items',
      'remaining_days': 'Remaining Days',
      'days': 'days',
      'no_notifications': 'No Notifications',
      'no_notifications_desc': 'Notifications will appear here when available',
      'mark_all_read': 'Mark all as read',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'older': 'Older',
      'arabic': 'Arabic',
      'english': 'English',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'push_notifications': 'Push Notifications',
      'push_notifications_desc': 'Receive notifications about sponsorships and updates',
      'app_version': 'App Version',
      'about': 'About',
      'contact': 'Contact Us',
      'logout_confirmation': 'Are you sure you want to logout?',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'password_changed': 'Password changed successfully',
      'member_since': 'Member since',
      'total': 'Total',
      'orphans': 'Orphans',
      'user': 'User',
      'name': 'Name',
      'financial': 'Financial',
      'educational': 'Educational',
      'medical': 'Medical',
      'completed': 'Completed',
      'inactive': 'Inactive',
      'ended': 'Ended',
      'help_center': 'Help Center',
      'help_intro_title': 'Welcome to Kafil App',
      'help_intro_desc': 'Kafil is a digital platform specialized in orphan sponsorship management. It enables benefactors to browse orphans in need of sponsorship, submit sponsorship requests, track ongoing sponsorships, and communicate with the organization. The app aims to make the sponsorship process easier, more transparent, and accessible.',
      'help_getting_started': 'Getting Started',
      'help_getting_started_desc': 'To start using the app, create a new account via the registration screen. Enter your full name, email, password, and phone number. After registration, you can log in using your email and password. If you already have an account, you can log in directly.',
      'help_dashboard': 'Home Dashboard',
      'help_dashboard_desc': 'The home screen displays an overview of your statistics: total orphans (sponsored by you + available for sponsorship), sponsored orphans, active sponsorships, and completed sponsorships. It also shows unsponsored orphans needing sponsorship. Use the quick action buttons to navigate to orphans, sponsorships, reports, and your profile. Note: Notifications are available for admin accounts only.',
      'help_orphans': 'Orphans Section',
      'help_orphans_desc': 'Browse the orphans list with three filter options: "All" shows orphans sponsored by you plus those available for sponsorship, "Sponsored" shows only your sponsored orphans, and "Needs Sponsorship" shows only available orphans. Use the search bar to find an orphan by name, and sort by newest, name, or age. Tap an orphan card to view full details. The status badge shows "Currently Sponsored" for active sponsorships, "Sponsorship stopped — needs a new sponsor" for ended ones, or "Needs Sponsorship" for unsponsored orphans.',
      'help_sponsorships': 'Sponsorships Section',
      'help_sponsorships_desc': 'This section displays all your sponsorships organized in three tabs: "Active" shows ongoing sponsorships, "Ended" shows ended or stopped sponsorships, and "History" shows all sponsorships. Submit a new sponsorship request by tapping the new sponsorship button. Select an orphan, choose the sponsorship type (Financial, Educational, Medical), and enter the monthly amount. Track your sponsorship journey through the timeline screen.',
      'help_reports': 'Reports & Statistics',
      'help_reports_desc': 'The reports section provides detailed statistics about your sponsorships: total sponsorships, active sponsorships, completed sponsorships, total amount donated, and average sponsorship duration. Pull down to refresh the data.',
      'help_notifications': 'Notifications',
      'help_notifications_desc': 'Notifications are available for admin accounts only. You receive notifications when a new sponsorship request is submitted or when a sponsorship status is updated. Tap a notification to mark it as read, or mark all as read from the menu button. Unread count appears on the bell icon on the home screen.',
      'help_profile': 'My Account',
      'help_profile_desc': 'From your profile screen you can view and edit your account information (name, email, phone, address). You can also change your password and view your personal statistics: active sponsorships, total donations, and number of sponsored orphans. You can also navigate to "About" and "Contact Us" pages. Note: The notifications option in the profile is available for admin accounts only.',
      'help_settings': 'Settings',
      'help_settings_desc': 'Through the settings screen you can change the app language between Arabic and English, switch between light, dark, and system theme modes, and enable or disable push notifications.',
      'help_faq': 'Frequently Asked Questions',
      'help_faq_q1': 'How can I sponsor an orphan?',
      'help_faq_a1': 'Go to the Orphans section, select an orphan that needs sponsorship, tap "Sponsor This Orphan Now", fill in the sponsorship request form, and submit it.',
      'help_faq_q2': 'How much does it cost to sponsor an orphan?',
      'help_faq_a2': 'You can choose the monthly amount you wish to contribute when submitting a sponsorship request. There is no mandatory minimum amount.',
      'help_faq_q3': 'How can I track my sponsorships?',
      'help_faq_a3': 'You can track all your sponsorships through the "My Sponsorships" tab in the bottom navigation bar. There you can view the status and details of each sponsorship.',
      'help_faq_q4': 'How can I contact support?',
      'help_faq_a4': 'You can contact the support team through the "Contact Us" section available in your profile menu, where you will find email addresses and phone numbers.',
      'help_contact': 'Technical Support',
      'help_contact_desc': 'If you encounter any issues or have any questions, feel free to contact the technical support team via email, phone, or WhatsApp available in the "Contact Us" section.',
    },
  };

  static String? _currentLocale = 'ar';

  static void setLocale(String locale) {
    _currentLocale = locale;
  }

  static String get(String key) {
    return _localized[_currentLocale]?[key] ?? _localized['ar']?[key] ?? key;
  }

  static String getLocale() => _currentLocale ?? 'ar';

  static bool get isRTL => _currentLocale == 'ar';
}

extension LocalizationExtension on BuildContext {
  String tr(String key) => AppStrings.get(key);
}
